version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./dockers/app/Dockerfile
  #   ports:
  #     - "13030:3030"

  server:
    build:
      context: .
      dockerfile: ./dockers/server/Dockerfile
    ports:
      - "18080:8080"
    env_file:
      - .env/.server
